### ISSUE TITLE
Replace plpythonu with plpython3u

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pycds#124]
pycds migration `4a2f1879293a` [creates several functions](https://github.com/pacificclimate/pycds/blob/master/pycds/alembic/versions/4a2f1879293a_create_functions.py) that use Python as the stored procedure language. It uses Python version 2 (i.e. plpythonu) which is no longer supported. I have reviewed these functions and they do not appear to use any syntax that's incompatible across version.

Simply replace `plpythonu` with `plpython3u`.

**Comment by rod-glover** [comment]
This should not be done until we have updated PostgreSQL _on our db servers_ to a version that supports `plpython3u`. At present our db servers are on PG ver 10, and it supports only `plpythonu`.

**Comment by rod-glover** [comment]
Correction: The `db.pcic` servers are now on PG 13, which supports `plpython3u`. The `dbnorth` server is on PG 10, but the databases it hosts (including Metnorth) will shortly be moved to `db.pcic`. So there's no reason not to go ahead with this. And it will mean a lot fewer testing headaches.
