### ISSUE TITLE
Query for materialized view `collapsed_vars_mv` is likely wrong

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#180]
This matview now contains rows with column `vars` with almost certainly undesirable values such as

```
lwe_thickness_of_precipitation_amountt: sum within months t: mean over years, ...
```

This is probably due to an unanticipated (but valid) change in the content of the `cell_method` column for some variables, which means the query for this view/matview is wrong.

At present, he conversion of each contributing `cell_method` column is expressed in SQLAlchemy by `func.regexp_replace(Variable.cell_method, "time: ", "_", "g")`. The intention of that replacement is apparently to create a conventional programming-language identifier. The obvious generalization would be to allow for any dimension preceding a colon (so, e.g., "t:"), and to replace all spaces with underscores. That generalization would still not handle all cases, but it would handle many more; it might also produce unfeasibly long identifiers.

Investigate, determine correct query, and create a migration to update the matview.

**Comment by rod-glover** [comment]
Let's consider what `CollapsedVariables` (`collapsed_vars_mv`, hereafter CV) is for. 
- CV is a matview, so evidently it is used to speed up otherwise infeasibly slow queries. 
- In PyCDS, CV is used in exactly one place, the view `CrmpNetworkGeoserver`.
- In the CRMP database, CV is used only in the legacy functions  `collapsed_vars_mv_refresh`, `collapsed_vars_mv_refresh_row`, which are used to maintain the legacy manual matview.
- In `pydap-extras`, CV is not used directly anywhere.
- In `pdp_util`, CV is not used directly anywhere.
- In `pdp`, CV is referred to in the documentation for how (now incorrectly; see above) an identifier is formed from the `standard_name` and `cell_method` columns.
- In `[station-data-portal-backend](https://github.com/pacificclimate/station-data-portal-backend)`, CV 

In turn, let's consider what `CrmpNetworkGeoserver` (`crmp_network_geoserver`, herafter CNG) is for.
- CNG is a view.
- CNG is documented in PyCDS as follows: "This view is used by the PDP Geoserver backend for generating station map layers." since the PDP Geoserver is no longer in service (its function has been replaced by markers in the Met Data Portal), we can discount this usage.
- In the CRMP database, CNG is not used directly anywhere.
- In `pydap-extras`, CNG is not used directly anywhere.
- In `pdp_util`, CNG is used in several places, but that usage is being corrected as part of https://github.com/pacificclimate/pdp_util/issues/50. That correction drives the present comment in the present issue.
- In `pdp`, CNG is not used directly anywhere in branches `master` or `pcds-only`. There is considerable mention of it in documentation, which should be removed. 
- In `[station-data-portal-backend](https://github.com/pacificclimate/station-data-portal-backend)`, CNG content is served by the endpoint `/crmp_network_geoserver`. That endpoint is not used by [`station-data-portal`](https://github.com/pacificclimate/station-data-portal), and IIRC, it was used only manually for experimental and debugging purposes.

Summary:
- CV is used only in the view `CrmpNetworkGeoserver`.
- CNG is used only in two places: 
  - In `pdp_util`, under correction.
  - In `station-data-portal-backend`, for unimportant, experimental purposes.

**Comment by jameshiebert** [comment]
Getting rid of code... I like it!

**Comment by rod-glover** [comment]
Key question: How should we update CV to support the driving use case, [#50](https://github.com/pacificclimate/pdp_util/issues/50)?

Answer:

The problem in pdp_util is a SQLAlchemy clause of the following form:

```
or_(CrmpNetworkGeoserver.vars.like("%within%"), CrmpNetworkGeoserver.vars.like("%over%"))
```

We need to replace it with an expression over all variables for a given (station) history of the form `variable_tags(Variable).contains(array['climatology'])`.

`CrmpNetworkGeoserver.vars` is reproduced directly from `CollapsedVariables.vars` for each history (`history_id`). Those vars columns roll up information from all variables related to a given history. That roll-up is more generally replaced by 
- a list (array) of in CV/CNG of all Variable id's
- plus a join of Variable against that list (that sounds tricky - research needed).

The same argument applies to `CNG.display_names` / `CV.display_names`.

Therefore our work here is simply to replace those columns in CV with an array aggregation of the relevant variable id's.

**Comment by rod-glover** [comment]
Forming an aggregate of the related variable id's is probably not the best way to do this: Use of that aggregate will always involve de-aggregating (`unnest`) it and then joining to Variable. But we already have an unaggregated version of this table -- indeed it is used in the definition of CV -- called `VarsPerHistory` (hereafter VPH). VPH is a simple many:many association of `History.history_id` to `Variable.vars_id`. So we'd be better off just using VPH in such a query.

But the existence of CV in addition to VPH implies that forming these aggregates is costly and that it is (was) worth preserving the results in a separate matview. In that case we need to replace the now-useless aggregate column `vars` with a more useful one such as `all_variable_tags`, which would aggregate (set/array union) values of `variable_tags(Variable)` over all variables per history into a single array, which can then be checked for whether it contains a specific value (e.g., 'climatology'). The expression 

```
or_(CrmpNetworkGeoserver.vars.like("%within%"), CrmpNetworkGeoserver.vars.like("%over%"))
```

would then be replaced directly by

```
CollapsedVariables.all_variable_tags(Variable).contains(array(['climatology']))
```

Under the assumption that it is still unfeasibly costly to compute the aggregates on the fly, this is the logical and lowest-effort correction. 

It is worth checking that assumption, however, as the alternative -- on the fly computations -- would allow us to drop this matview altogether. @jameshiebert , do you have any thoughts about this?

**Comment by rod-glover** [comment]
A further complication -- the usage of CNG/CV in pdp_util at present may require such a pre-aggregated form; in order to unaggregate it, code in pdp_util may have to be revised considerably, which would require effort and risk errors. That alone may drive the decision.

**Comment by rod-glover** [comment]
At present I'm headed for the lowest-effort version, which is to update CV with a new column `all_variable_tags`, defined as follows:

```
with xxx as (
select 
    distinct
    history_id, 
    unnest(variable_tags(meta_vars)) as a
from vars_per_history_mv natural join meta_vars
)
select
    history_id,
    array_agg(a order by a)
from xxx
group by history_id
order by history_id
```

There is probably a tighter way to do this, but this at least works, and can form the basis for a tighter formulation.

**Comment by rod-glover** [comment]
Executing these queries against the full CRMP database is not _very_ time-consuming, < 1 s. It seems as if the maintenance of CV as a matview might be unnecessary, and it could be packaged as a view.

I'm also planning to define the uncollapsed query `collapsed_vars_array_v` as a view, since it may have some utility in future, and hiding it as a CTE inside another query seems counterproductive.

**Comment by rod-glover** [comment]
On further thought, there's no current need to establish `aggregated_vars` as an independently standing view. If it turns out it would be useful, we can extract it as a view later. Less overhead.
