### ISSUE TITLE
Make test data optional in `mktestdb.py` script

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pycds#22]
The [`mktestdb.py`](https://github.com/pacificclimate/pycds/blob/master/scripts/mktestdb.py) script creates an empty database with the PyCDS/crmp schema and then [populates it with test data](https://github.com/pacificclimate/pycds/blob/master/scripts/mktestdb.py#L24). However, often (more often than not) we want *just* the tables and nothing else.

For this issue, please create a command line option (`--include-data`) to the script. By default, it should be false. But if used, the data should be created as well.

**Comment by jameshiebert** [comment]
@nikola-rados Can you take this on?

**Comment by nikola-rados** [comment]
Absolutely, I will get right on it.
