### ISSUE TITLE
Make CollapsedVars.vars robust to null cell_method

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#28]
At present writing, there is no `CollapsedVars` materialized view. Issue #26 will add this, and it should be done first.

The definition for the materialized view is

```
SELECT 
    vars_per_history_mv.history_id, 
    array_to_string(array_agg(meta_vars.standard_name::text || regexp_replace(meta_vars.cell_method::text, 'time: '::text, '_'::text, 'g'::text)), ', '::text) AS vars, 
    array_to_string(array_agg(meta_vars.display_name), '|'::text) AS display_names
FROM vars_per_history_mv
    NATURAL JOIN meta_vars
GROUP BY vars_per_history_mv.history_id
```

The subexpression 

```
meta_vars.standard_name::text || regexp_replace(meta_vars.cell_method::text, 'time: '::text, '_'::text, 'g'::text)
``` 

yields `null` when `standard_name` or `cell_method` is `null`. In turn, this contributes nothing (no string) to the result of `array_to_string` which is the value of `vars`.

This is acceptable for `standard_name`, but we wish not to return null (and hence no contribution to `vars`) for null `cell_method`. Instead, null `cell_method` should be treated as the empty string in this subexpression, with the effect that `standard_name` is the result and is included in `vars`.

**Comment by rod-glover** [comment]
Alternatively, or additionally, [add NOT NULL constraints](https://github.com/pacificclimate/pycds/issues/29).

**Comment by faronium** [comment]
If they are required to be NOT NULL (the requirement sounds fine to me) then will there need to be a default value? I would suggest as defaults: "foo: bar" for cell method, "foo_bar" for standard name and "foo bar" for display name. Or, something that would make searching for unedited meta_vars entries easy.

**Comment by rod-glover** [comment]
@faronium : Interesting. My intention was actually to force a valid definition of a variable from the outset. Assigning dummy values instead of null does prevent certain null-related problems from occurring in our code, but it still allows conceptually invalid variables to be defined. 

Is it important to be able to create a variable without fully defining it? Your suggestion implies it is, but it's worth asking how and why, I think.
