### ISSUE TITLE
Add NOT NULL constraints to certain Variable columns

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#29]
This writer's naive view is that the following columns are essential to defining a variable, and should not be allowed to have null values:

- `standard_name`
- `cell_method`
- `display_name`

**Comment by rod-glover** [comment]
The main reason for doing this is to eliminate the need for #28 . If we do this, we will have to migrate all current CRMP/PyCDS based databases, namely CRMP, dbnorth/metnorth, and dbmsc.

**Comment by rod-glover** [comment]
@faronium said in a different issue:

> If they are required to be NOT NULL (the requirement sounds fine to me) then will there need to be a default value? I would suggest as defaults: "foo: bar" for cell method, "foo_bar" for standard name and "foo bar" for display name. Or, something that would make searching for unedited meta_vars entries easy.

**Comment by rod-glover** [comment]
@faronium : Interesting. My intention was actually to force a valid definition of a variable from the outset. Assigning dummy values instead of null does prevent certain null-related problems from occurring in our code, but it still allows conceptually invalid variables to be defined. 

Is it important to be able to create a variable without fully defining it? Your suggestion implies it is, but it's worth asking how and why, I think.

**Comment by faronium** [comment]
Well, for me sometimes it's about getting small dabs of work done here and there and then coming back later to finish the task. In that case, it's simple to fill out much of the table, but sometimes coming up with standard_names and cell_methods can be challenging. But, mostly I agree that it's not that high a hurdle so maybe one should be required to leap it when adding new variables to the table(s)

**Comment by rod-glover** [comment]
I'd definitely prefer that, but it's not up to me to be dictating process to you or other scientists, except when absolutely necessary. This isn't quite one of those cases. Your call.

**Comment by faronium** [comment]
I edit meta_vars by hand/GUI using pgadmin, how will a NOT NULL requirement look when editing in that way?

**Comment by rod-glover** [comment]
When you try to save the changes (e.g., inserting a new variable) pgAdmin III gives you a dialog with the message "An error has occurred: 01:22:21 PM: Error: ERROR:  null value in column "<name>" violates not-null constraint" and sends you back to the editing screen. Would that be OK?

**Comment by faronium** [comment]
sounds good. I'm okay with implementing the requirement
