### ISSUE TITLE
Modify PyCDS to bring it closer to current state of CRMP

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#30]
Modify PyCDS to bring it closer to current state of CRMP 

We are deliberately omitting all items (tables, functions, triggers, views)
that support the old manual materialized views, as these are shortly to be 
supplanted by native matviews. The matview tables themselves are retained,
since they will continue to exist as native matviews.

Also in question is the value of defining many of the functions and views
below: They may be either CRMP-specific, or simply ephemera. Eliminate any
not worth propagating into new databases.

Add the following:

- Functions
  - See `pycds/weather_anomaly.py#71` for an example of how to create a function.
  - [x] check for existing code in PyCDS
  - [x] categorize these functions as:
    - in use in production software (P)
    - generally useful (G)
    - used for analysis, report generation (A)
    - not used (N)
  - [x] `closest_stns_within_threshold` (??) defined in repo crmp; but replicated as a query (not this function) in crmprtd; see [search](https://github.com/search?q=closest_stns_within_threshold+in%3Afile+org%3Apacificclimate&type=Code)
  - [x] `daily_ts` (P?: crmp) see [search](https://github.com/search?q=daily_ts+in%3Afile+org%3Apacificclimate&type=Code) 
  - [x] `daysinmonth` (P: pycds/weather_anomaly.py, pydap.handlers.pcic) see [search](https://github.com/search?q=daysinmonth+in%3Afile+org%3Apacificclimate&type=Code)
  - [x] `do_query_one_station` (??) in crmp, but comments suggest it is only an example for `query_one_station` 
  - [x] `getstationvariabletable` (P: function query_one_station, query_one_station_climo) NB: This is not defined in code anywhere; it must have been manually inserted.
  - [x] `lastdateofmonth` (N: see [search](https://github.com/search?q=lastdateofmonth+in%3Afile+org%3Apacificclimate&type=Code))
  - [x] `monthly_ts` (N: see [search](https://github.com/search?q=monthly_ts+in%3Afile+org%3Apacificclimate&type=Code))
  - [x] `query_one_station` (P: pydap.handlers.pcic, pcds_ml, crmp)
  - [x] `query_one_station_climo` (P: pydap.handlers.pcic) NB: no corresponding `do_xxx`
  - [x] `season` (??: crmp; see [code](https://github.com/pacificclimate/crmp/blob/96d4885e288ded21a93168d14077f7b43e2b5ac5/database/views/time_aggregates.sql)) 
  - [x] `updatesdateedate` (G: looks useful: `updates meta_station.min/max_obs_time`, see #19)
- Manual materialized view tables
  - just mappings onto these tables; no support for the infrastructure that makes them matviews
  - [x] `collapsed_vars_mv`
  - [x] `station_obs_stats_mv`
- Regular tables
  - These tables are in the CRMP database but have not been mapped by PyCDS. Why?
  - [x] `meta_alias` -- 0 rows; not used in code; no evident application at PCIC => do not model
  - [x] `meta_climo_attrs` -- 53324 rows; not used in code; Faron advises to keep
  - [x] `stats_station_var` -- 125k rows; used in crmp/scripts; ephemeral, no longer needed, remove
  - [x] `time_bounds` -- 144040 rows; time bounds on `time: sum` and similar non-point observations (e.g., Accumulated Rainfall); keep
- Indexes
  - [x] `climo_obs_count_idx` (table `climo_obs_count_mv`)
  - [x] `collapsed_vars_idx`  (table `collapsed_vars_mv`)
  - [x] `meta_climo_attrs_idx`  (table `meta_climo_attrs`)
  - [x] `fki_meta_history_station_id_fk`  (table `meta_history`)
  - [x] `meta_history_freq_idx`  (table `meta_history`)
  - [x] `fki_meta_station_network_id_fkey`  (table `meta_station`)
  - [x] `fki_meta_vars_network_id_fkey`  (table `meta_vars`)
  - [x] `obs_count_per_month_history_idx`  (table `obs_count_per_month_history_mv`)
  - [x] `flag_index`  (table `obs_raw_native_flags`)
  - [x] `pcic_flag_index`  (table `obs_raw_pcic_flags`)
  - [x] `station_obs_stats_mv_idx`  (table `station_obs_stats_mv`)
  - [x] `var_hist_idx`  (table `vars_per_history_mv`)
- Views: See #34 

Other questions:
- What is table `meta_network_geoserver` for? Not referenced anywhere in PyCDS. Looks useless. Drop (later)?
- What is table `obs_derived_values` for? Is anyone using it?
- `VarsPerHistory`: columns are marked as primary keys in PyCDS but not in CRMP. Which is right?
  - If they should be primary keys, then some other matviews lacking primary keys should follow suit.

Additional TODOs:

- [x] Don’t emit CREATE TABLE statements for Views: https://alembic.sqlalchemy.org/en/latest/cookbook.html#don-t-emit-create-table-statements-for-views 

Notes:
- Re. views: https://stackoverflow.com/questions/9766940/how-to-create-an-sql-view-with-sqlalchemy

**Comment by rod-glover** [comment]
This comes even before installing Alembic, since it will result in PyCDS representing the existing state of the CRMP database that we wish to propagate forward. Once that representation is established, we can then introduce Alembic and create the initial migration from empty database to the full, current CRMP schema.

**Comment by rod-glover** [comment]
@faronium , I have some questions about the items named above. Specifically can you comment on the following:

1. Functions:
   1.  Are any of these known to you to be important to have in other databases with the same schema (i.e., which are _not_ specific to just CRMP)? Which ones?
   1. Are any of these known to you to be either CRMP specific or just ephemeral, experiments, leftovers, etc.? Which ones?

1. Regular tables: Can you comment on the utility, value, continued need for these? I don't want to change the schema unnecessarily, but I would like to know about any tables that are useless or mistaken or otherwise not desired to continue in the schema.

1. Views: Same questions as for functions above.

**Comment by faronium** [comment]
See attached files for a start. 

[views_and_tables_priorities_doc.docx](https://github.com/pacificclimate/pycds/files/3799115/views_and_tables_priorities_doc.docx)

**Comment by jameshiebert** [comment]
Would it be a good idea to re-frame the question a bit? I suspect that we should treat differently tables/views that are used programmatically by production software and tables/views that are used for direct scientific analysis (either one-offs, or report generation or whatever). So the question maybe requires a more detailed answer than "does this get used by anyone, ever".

I suspect that we could manage a lot of the latter category of views separately than we would the former category. For example views can be owned or created by a specific user that wants to use them.

**Comment by rod-glover** [comment]
@jameshiebert , I agree. I have been thinking this question, though I didn't write it down clearly.

**Comment by rod-glover** [comment]
@jameshiebert , I think the outstanding questions can be reduced to the following. Can you comment?

1. Do we need table `stats_station_var` in the ORM? Faron says to consult you.
1. Do we need table `meta_network_geoserver` in the ORM? No production code (that I can find) references it. Not to be confused with the rather important `crmp_network_geoserver`.

As noted above, I am deferring views to a separate issue/PR.

**Comment by jameshiebert** [comment]
`stats_station_var` *was* used for analysis in a report from many many years ago. It is not longer in use.

I have no knowledge of any use of `meta_network_geoserver`. Probably safe to turf it.
