### ISSUE TITLE
Make PyCDS schema (name) agnostic

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#32]
I recall having a lot of trouble with working within the correct schema (in the sense of PostgreSQL: a collection of tables, etc. within a database) when working on PyCDS 2+ years ago. I suspect it was just ignorance about how to use `search_path`. There is some particularly gorky-looking code in `scripts/manage-views.py` relating to `search_path`. This all needs to be renovated to be schema-agnostic.

**Comment by rod-glover** [comment]
Hmm. Except, for [this advice](https://github.com/sqlalchemy/alembic/issues/569#issuecomment-497693528) from the author of SQLAlchemy. It refers to [this bit](https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#remote-schema-table-introspection-and-postgresql-search-path) of the SQLAlchemy documentation.

The short version seems to be that Alembic will be unhappy if you use the search path to establish the schema. Instead, you are supposed to code it directly in, along the lines of the hardcoded 'crmp' schema name.

As distasteful as this seems on first glance, I definitely don't want to mess up Alembic, which is central to the larger effort on PyCDS.

I'll investigate how we can parametrize the schema so that we are not stuck with hardcoding.

**Comment by rod-glover** [comment]
Hmm. This is proving quite challenging. The reason is that the only way to establish the schema in which tables and other other objects are created using the declarative base is by setting that name when the declarative base object is created, thus: 

```
Base = declarative_base(metadata=MetaData(schema='name'))
```

This object, a class, is used as the base class for all table declarations, thus:

```
class Table(Base):
    ...
```
None of the following things has any effect on the schema Table is defined in. In every case it is defined in the original schema, `name`.

```
Base.metadata.schema = 'different_name'
Table.metadata.schema = 'different_name'
Table.__table__.schema = 'different_name'
```

These attributes all take and hold the values, but the assignment of table to schema appears to happen at class declaration time, i.e., before any programmatic intervention, despite the fact that the tables are not actually created until a statement such as the following is executed:

```
Base.metadata.create_all(bind=engine)
```

I have not been able to find any parameters to `create_all` that would allow changing this behaviour. Nor do there seem to be any `set_schema()` type functions for Base, Table, etc.

The only solution I can think of at present is pretty heavy-weight: We could turn the static SQLAlchemy declarations into a factory, using `type` to create the SQLAlchemy classes instead. The result would be an object with the SQLAlchemy classes as members. This seems undesirable for several reasons, the most serious, apart from sheer effort, would be the probable complete discombobulation of Alembic by this arrangement.

**Comment by jameshiebert** [comment]
Well, crap. I can see how that would be a problem (and maybe a downside of the metaprogramming approach that SQLAlchemy takes. Thanks for thoroughly researching the problem and I guess if we can't parametrize it, then that's good to know and we can move on with our lives. I'll try to remember to bite my tongue when I'm about to complain about the hard-coded schema :)

**Comment by rod-glover** [comment]
An alternative, that might be workable, is to call "out" for the schema name where `Base` is declared. 

By "out", I mean external to the program using PyCDS. The natural idea is to get it from an environment variable, with a fallback to 'crmp' if the env var is not set. I have done this and it works. But it may be unwieldy in certain situations. Currently I am tussling with test setups, but I believe the idea is sound and workable.

**Comment by jameshiebert** [comment]
Seems sensible! I'd love to see an implementation.
