### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pycds#33]
This code has a lot of non-compliance with PEP 8. Even just partially bringing this code to PEP 8 would be an improvement. At minimum, line length compliance.

**Comment by jameshiebert** [comment]
I'd recommend the [Python Black](https://pypi.org/project/black/) tool for a first pass (or even for subsequent upkeep!) at this.

**Comment by rod-glover** [comment]
Also conversion of string formatting to f-strings.

**Comment by rod-glover** [comment]
Check TODOs. There are definitely a few that fall into the category of cleanup.
